name       : python3-sip
version    : 4.19.2
release    : 6
source     :
    - https://downloads.sourceforge.net/project/pyqt/sip/sip-4.19.2/sip-4.19.2.tar.gz : 432b4aad25254e6997913e33b1ca3cf5fd21d5729a50a3ce2edccbea82c80533
license    : GPL-3.0
component  : programming.python
summary    : python3-sip is a tool that creates python3 bindings for C and C++ libraries.
description: |
    python3-sip is a tool that creates python3 bindings for C and C++ libraries.
builddeps  :
    - pkgconfig(python-3.5)
    - python-sip
rundeps    :
    - python-sip
setup      : |
    python3 configure.py CFLAGS="${CFLAGS}"
build      : |
    %make
install    : |
    %make_install -C siplib
