name       : python3-sip
version    : 4.19.2
release    : 7
source     :
    - https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.2/sip-4.19.2.tar.gz : 432b4aad25254e6997913e33b1ca3cf5fd21d5729a50a3ce2edccbea82c80533
license    : GPL-3.0
component  : programming.python
summary    : python3-sip is a tool that creates python3 bindings for C and C++ libraries.
description: |
    python3-sip is a tool that creates python3 bindings for C and C++ libraries.
builddeps  :
    - pkgconfig(python-3.5)
    - python-sip
rundeps    :
    - python-sip
setup      : |
    sed -i "s|sip_bin_dir, \"sip\"|sip_bin_dir, \"sip3\"|" configure.py
    python3 configure.py CFLAGS="${CFLAGS}"
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/bin/{sip,sip3}
