name       : python3-sip
version    : 4.19.13
release    : 13
source     :
    - https://netcologne.dl.sourceforge.net/project/pyqt/sip/sip-4.19.13/sip-4.19.13.tar.gz : e353a7056599bf5fbd5d3ff9842a6ab2ea3cf4e0304a0f925ec5862907c0d15e
license    : GPL-3.0-or-later
component  : programming.python
summary    : python3-sip is a tool that creates python3 bindings for C and C++ libraries
description: |
    SIP is a tool for generating bindings for C++ classes so that they can be
    accessed as normal Python classes. SIP takes many of its ideas from SWIG but,
    because it is specifically designed for C++ and Python, is able to generate
    tighter bindings. SIP is so called because it is a small SWIG.
builddeps  :
    - pkgconfig(python3)
    - python-sip
rundeps    :
    - python-sip
setup      : |
    python3 configure.py --sip-module PyQt5.sip CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install -j1
    mv $installdir/usr/bin/{sip,sip3}
