name       : python3-sip
version    : 4.19
release    : 5
source     :
    - http://downloads.sourceforge.net/project/pyqt/sip/sip-4.19/sip-4.19.tar.gz : 014bf55f653e0d8bcc582705ef4fbd61e0859a36e959ab46d8fa060cdf0b5e27
license    : GPL-3.0
component  : programming.python
summary    : python3-sip is a tool that creates python3 bindings for C and C++ libraries.
description: |
    python3-sip is a tool that creates python3 bindings for C and C++ libraries.
builddeps  :
    - pkgconfig(python-3.5)
    - python-sip
rundeps    :
    - python-sip
setup      : |
    python3 configure.py CFLAGS="${CFLAGS}"
build      : |
    %make
install    : |
    %make_install -C siplib
